name: Deploy

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

# Kill already running jobs after a new push
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  node-version: "14.17"

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout pull request
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Checkout main branch
        uses: actions/checkout@v2
        if: github.ref == 'refs/heads/main'
        with:
          persist-credentials: false

      - name: Create a cache folder for node and npm
        id: npm-cache
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules-${{ env.node-version }}-acceptance-4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"

      - name: Upgrade NPM
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install -g npm@7

      - name: Show NPM version
        run: npm --version

      - name: Show Node.js version
        run: node --version

      - name: Show git version
        run: git --version

      - name: NPM install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install --loglevel=error --audit=false --ignore-scripts

      - name: Build nuxt 3
        run: npm run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          cname: www.crossyourhe.art
